name: observable-ai-agent
services:
  tempo:
    restart: unless-stopped
    image: grafana/tempo:2.7.2
    container_name: tempo
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ../tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"

  otel-collector:
    restart: unless-stopped
    image: otel/opentelemetry-collector-contrib:0.129.1
    container_name: otel-collector
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ../otel/otel-collector.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  grafana:
    restart: unless-stopped
    image: grafana/grafana:12.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - tempo
volumes:
  grafana-storage:
  tempo-data: