services:
  tempo:
    image: grafana/tempo:2.7.2
    container_name: tempo
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ../tempo/tempo.yaml:/etc/tempo.yaml:Z
    ports:
      - "3200:3200"
      - "4317:4317"

  otel-collector:
    image: otel/opentelemetry-collector:0.129.1
    container_name: otel-collector
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ../otel/otel-collector.yaml:/etc/otelcol/config.yaml:Z
    ports:
      - "4318:4318"
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning:Z
    depends_on:
      - tempo